### ISSUE TITLE
Is this ready for Mechanic 2?

### ISSUE THREAD

**Issue by justvanrossum** [roboDocs/interpolationMatrix#1]
The code is ready enough. (There are bugs, but I think the basic functionality is alright.)

I have no experience with Mechanic, so please advice if there's anything missing/wrong for deployment.

**Comment by gferreira** [comment]
hi Just. yes, I think it’s ready for Mechanic. I’ll update the [extension metadata](http://github.com/robofont-mechanic/mechanic-2-server/blob/gh-pages/_data/interpolationMatrix.yml) in the Mechanic2 server.

**Comment by justvanrossum** [comment]
Awesome, thanks!

**Comment by gferreira** [comment]
see [switching Interpolation Matrix to RoboDocs version](https://github.com/robofont-mechanic/mechanic-2-server/pull/17/files)

**Comment by gferreira** [comment]
thanks @typemytype for merging the changes to the extension data.
I’ve made some small edits (py3/fontParts syntax, README) and added html docs.
